_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.11.12
            "5": 0.19.11
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": linux-x86_64
